name: scriptview.js CI

on:
  push:
    branches: [master]
#  pull_request:
#    branches: [master]

jobs:
  build:
    runs-on: self-hosted # Update this based on your self-hosted runner configuration

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} # If you need a matrix, add it here
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build Frontend
        working-directory: frontend
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        run: |
          echo "VITE_BASE_URL=${VITE_BASE_URL}" > .env
          rm -rf node_modules
          npm install
          npm run build

      - name: Install Backend
        working-directory: backend
        env:
          ORIGIN: ${{ secrets.ORIGIN }}
          DB_URI: ${{ secrets.DB_URI }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          echo -e "DB_URI=${DB_URI}\nORIGIN=${ORIGIN}\nNODE_ENV=${NODE_ENV}" > .env
          rm -rf node_modules
          npm install
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
